import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const usePlayerEndScreenStyles = makeStyles({
  overlay: {
    position: "absolute",
    inset: "0",
    zIndex: "10",
    backgroundColor: "rgba(8,8,8,0.92)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "28px",
    padding: "24px",
  },
  label: {
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.3)",
  },
  cards: {
    display: "flex",
    flexDirection: "row",
    gap: "12px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    width: "120px",
    gap: "6px",
    textDecoration: "none",
    cursor: "pointer",
    transitionProperty: "transform, opacity",
    transitionDuration: tokens.transitionSlow,
    ":hover": {
      transform: "scale(1.04)",
      opacity: "0.9",
    },
  },
  cardPoster: {
    width: "120px",
    height: "68px",
    borderRadius: tokens.radiusSm,
    backgroundSize: "cover",
    backgroundPosition: "center top",
    backgroundImage: "linear-gradient(135deg, #1a0a0a 0%, #2d0d10 100%)",
    border: "1px solid rgba(255,255,255,0.08)",
    flexShrink: "0",
  },
  cardTitle: {
    fontSize: "11px",
    fontWeight: "600",
    color: tokens.colorText,
    lineHeight: "1.3",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: "2",
    WebkitBoxOrient: "vertical",
  },
  cardYear: {
    fontSize: "10px",
    color: "rgba(255,255,255,0.3)",
  },
  actions: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    alignItems: "center",
  },
  replayBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 20px",
    backgroundColor: "transparent",
    border: `1px solid rgba(255,255,255,0.18)`,
    borderRadius: tokens.radiusSm,
    color: "rgba(255,255,255,0.6)",
    fontSize: "12px",
    fontWeight: "600",
    fontFamily: "inherit",
    cursor: "pointer",
    transitionProperty: "color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      border: "1px solid rgba(255,255,255,0.35)",
    },
  },
});
