import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useSettingsStyles = makeStyles({
  shell: {
    height: "100%",
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  nav: {
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg1,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
  },
  navHeading: { marginBottom: "14px" },
  navItem: {
    paddingTop: "9px",
    paddingBottom: "9px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontSize: "12px",
    textAlign: "left",
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    transitionProperty: "background-color, color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },
  navItemActive: {
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    ":hover": {
      color: tokens.colorGreen,
    },
  },
  body: {
    overflowY: "auto",
    paddingTop: "32px",
    paddingBottom: "32px",
    paddingLeft: "40px",
    paddingRight: "40px",
  },
  sectionEyebrow: { color: tokens.colorGreen },
  sectionTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "40px",
    color: tokens.colorText,
    marginTop: "12px",
    marginBottom: "24px",
    textTransform: "uppercase",
    letterSpacing: "-0.01em",
  },
  sectionWrap: { maxWidth: "640px" },
});
