import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const usePlayerSidebarStyles = makeStyles({
  root: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: "290px",
    backgroundColor: tokens.colorBg1,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.colorBorder,
    display: "flex",
    flexDirection: "column",
    overflowX: "hidden",
    overflowY: "hidden",
    zIndex: 20,
    boxShadow: "-12px 0 32px rgba(0,0,0,0.45)",
    transform: "translateX(0)",
    opacity: 1,
    transitionProperty: "transform, opacity",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
  },
  rootHidden: {
    transform: "translateX(100%)",
    opacity: 0,
    pointerEvents: "none",
  },

  closeBtn: {
    position: "absolute",
    top: "12px",
    right: "12px",
    width: "26px",
    height: "26px",
    borderRadius: "999px",
    backgroundColor: "rgba(0,0,0,0.35)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.18)",
    borderRightColor: "rgba(255,255,255,0.18)",
    borderBottomColor: "rgba(255,255,255,0.18)",
    borderLeftColor: "rgba(255,255,255,0.18)",
    color: tokens.colorTextDim,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 25,
  },

  header: {
    paddingTop: "20px",
    paddingBottom: "14px",
    paddingLeft: "18px",
    paddingRight: "18px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
  },
  nowPlayingEyebrow: {
    color: tokens.colorGreen,
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "26px",
    color: tokens.colorText,
    marginTop: "8px",
    letterSpacing: "-0.01em",
    lineHeight: "1",
    textTransform: "uppercase",
  },
  meta: {
    fontSize: "11px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.08em",
    marginTop: "6px",
    textTransform: "uppercase",
  },
  plot: {
    fontSize: "11px",
    color: tokens.colorTextDim,
    marginTop: "10px",
    lineHeight: "1.5",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflowY: "hidden",
  },
  episodeRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    marginTop: "10px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
  episodeCode: {
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderRadius: tokens.radiusSm,
    fontWeight: 600,
  },
  episodeTitle: {
    color: tokens.colorText,
    textTransform: "none",
    letterSpacing: "0.04em",
  },

  body: {
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "18px",
    paddingRight: "18px",
    flexGrow: 1,
    overflowY: "auto",
  },
  bodyEyebrow: {
    marginBottom: "10px",
  },
  upNextEmpty: {
    fontSize: "11px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
  },
  upNextRow: {
    display: "grid",
    gridTemplateColumns: "44px 1fr 22px",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    alignItems: "center",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    textDecorationLine: "none",
  },
  upNextPoster: {
    width: "44px",
    height: "62px",
    objectFit: "cover",
    backgroundColor: tokens.colorBorder,
  },
  upNextInfo: {
    minWidth: 0,
  },
  upNextTitle: {
    fontSize: "12px",
    color: tokens.colorText,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  upNextSub: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    marginTop: "2px",
  },
  upNextPlay: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreenDeep,
    borderRightColor: tokens.colorGreenDeep,
    borderBottomColor: tokens.colorGreenDeep,
    borderLeftColor: tokens.colorGreenDeep,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textDecorationLine: "none",
  },

  footer: {
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingLeft: "18px",
    paddingRight: "18px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    display: "flex",
    columnGap: "8px",
  },
  vlcBtn: {
    flexGrow: 1,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "10px",
    paddingRight: "10px",
    backgroundColor: "transparent",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    cursor: "pointer",
  },
  backBtn: {
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: tokens.colorSurface2,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    borderRadius: "2px",
    textTransform: "uppercase",
    cursor: "pointer",
  },
});
