import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useFeedbackStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 24px",
    overflow: "auto",
  },
  card: {
    width: "100%",
    maxWidth: "480px",
    backgroundColor: tokens.colorSurface,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusLg,
    padding: "28px",
  },
  heading: {
    fontFamily: tokens.fontHead,
    fontSize: "26px",
    letterSpacing: "0.06em",
    color: tokens.colorWhite,
    marginBottom: "4px",
  },
  sub: {
    fontSize: "12px",
    color: tokens.colorMuted,
    marginBottom: "24px",
    lineHeight: "1.6",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBottom: "16px",
  },
  label: {
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.colorMuted2,
  },
  select: {
    width: "100%",
    padding: "9px 12px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontFamily: tokens.fontBody,
    outlineStyle: "none",
    cursor: "pointer",
    appearance: "none",
    boxSizing: "border-box",
    ":focus": {
      border: `1px solid ${tokens.colorRed}`,
    },
  },
  textarea: {
    width: "100%",
    padding: "9px 12px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontFamily: tokens.fontBody,
    outlineStyle: "none",
    resize: "vertical",
    minHeight: "120px",
    lineHeight: "1.6",
    boxSizing: "border-box",
    ":focus": {
      border: `1px solid ${tokens.colorRed}`,
    },
    "::placeholder": {
      color: tokens.colorMuted2,
    },
  },
  submitBtn: {
    width: "100%",
    padding: "10px 0",
    backgroundColor: tokens.colorRed,
    border: `1px solid ${tokens.colorRed}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0.04em",
    cursor: "pointer",
    transitionProperty: "background",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorRedDark,
    },
    ":disabled": {
      opacity: "0.5",
      cursor: "default",
    },
  },
  successMsg: {
    fontSize: "12px",
    color: tokens.colorGreen,
    marginTop: "12px",
    textAlign: "center",
  },
  hidden: {
    display: "none",
  },
});
