import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useEmptyLibrariesHeroStyles = makeStyles({
  root: {
    position: "relative",
    flexGrow: 1,
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: "80px",
    // Header floats absolute over the page; clear it plus leave breathing
    // room above the eyebrow so it doesn't crowd the AppHeader chrome.
    paddingTop: `calc(${tokens.headerHeight} + 48px)`,
    boxSizing: "border-box",
    overflow: "hidden",
    backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.045) 1px, transparent 1px)",
    backgroundSize: "28px 28px",
  },
  watermark: {
    position: "absolute",
    bottom: "-60px",
    right: "-60px",
    fontFamily: tokens.fontHead,
    fontSize: "340px",
    lineHeight: "1",
    letterSpacing: "-0.02em",
    color: "rgba(255,255,255,0.022)",
    pointerEvents: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
  },
  content: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  headline: {
    display: "flex",
    flexDirection: "column",
    fontFamily: tokens.fontHead,
    fontSize: "96px",
    lineHeight: "0.9",
    letterSpacing: "0.01em",
    textTransform: "uppercase",
  },
  headlineWhite: { color: tokens.colorText },
  headlineAccent: { color: tokens.colorGreen },
  rule: {
    width: "56px",
    height: "3px",
    backgroundColor: tokens.colorGreen,
    borderRadius: "2px",
  },
  body: {
    fontSize: "14px",
    lineHeight: "1.65",
    color: tokens.colorTextDim,
    maxWidth: "360px",
    margin: 0,
    fontFamily: tokens.fontBody,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    marginTop: "8px",
  },
  cta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  hint: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.12em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
  },
});
